FROM redhat/ubi8:8.10-1184

WORKDIR /app

RUN yum install -y curl gcc cmake

RUN yum install -y python38 python38-devel && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.8 get-pip.py

CMD ["/bin/bash", "-c", "\
    python3.8 -m pip install -r requirements.txt \
    && python3.8 -m pip install nuitka patchelf \
    && rm -rf build \
    && cmake -B build -S . \
    && make -C build standalonebinary \
"]