name: Rebase liangdin-test on top of amd-mainline
on:
    workflow_dispatch:
    schedule:
      - cron: 0 0 * * 1

jobs:
  promote-dev-to-stg:
    if: github.repository == 'ROCm/rocprofiler-compute'
    runs-on: ubuntu-latest
    name: Rebase liagndin-test on top of amd-mainline
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ROCPROFILER_COMPUTE_RUNNER_APP_APP_ID }}
          private-key: ${{ secrets.ROCPROFILER_COMPUTE_RUNNER_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: '0'
          token: ${{ steps.generate-token.outputs.token }}

      - name: Rebase
        run: |
          git checkout liangdin-test
          git rebase origin/amd-mainline
          git push origin HEAD
